# 矩阵和方程组
## 线性方程

### Exercise

*****
1.使用随机生成的$4\times4$矩阵$A$,$B$.计算下面矩阵，并确定哪些矩阵是相等的。

In [1]:
A = rand(4,4)

4×4 Array{Float64,2}:
 0.757516  0.707448   0.496353  0.344774
 0.23901   0.83478    0.37416   0.373502
 0.464154  0.0547248  0.115363  0.654543
 0.804421  0.354907   0.717205  0.528064

In [2]:
B = rand(4,4)

4×4 Array{Float64,2}:
 0.893909   0.557959  0.568323  0.0367486
 0.549221   0.144837  0.763599  0.393109
 0.0981079  0.935241  0.589028  0.552994
 0.802547   0.286322  0.501098  0.456753

In [3]:
A * B

4×4 Array{Float64,2}:
 1.39109   1.08805   1.43585   0.737899
 1.00859   0.711136  1.18082   0.714449
 0.981587  0.562207  0.701519  0.401329
 1.40816   1.32219   1.41524   0.806884

In [4]:
B * A

4×4 Array{Float64,2}:
 1.10386  1.14231   0.744379  0.907992
 1.12131  0.690757  0.69683   0.950849
 1.01609  1.07862   0.863188  1.0607
 1.27638  0.996304  0.89087   0.952824

In [6]:
Array((A' * B')')

4×4 Array{Float64,2}:
 1.10386  1.14231   0.744379  0.907992
 1.12131  0.690757  0.69683   0.950849
 1.01609  1.07862   0.863188  1.0607
 1.27638  0.996304  0.89087   0.952824

In [7]:
Array((B' * A')')

4×4 Array{Float64,2}:
 1.39109   1.08805   1.43585   0.737899
 1.00859   0.711136  1.18082   0.714449
 0.981587  0.562207  0.701519  0.401329
 1.40816   1.32219   1.41524   0.806884

In [8]:
Array(A' * B')

4×4 Array{Float64,2}:
 1.10386   1.12131   1.01609   1.27638
 1.14231   0.690757  1.07862   0.996304
 0.744379  0.69683   0.863188  0.89087
 0.907992  0.950849  1.0607    0.952824

In [9]:
Array((A * B)')

4×4 Array{Float64,2}:
 1.39109   1.00859   0.981587  1.40816
 1.08805   0.711136  0.562207  1.32219
 1.43585   1.18082   0.701519  1.41524
 0.737899  0.714449  0.401329  0.806884

In [10]:
Array(B' * A')

4×4 Array{Float64,2}:
 1.39109   1.00859   0.981587  1.40816
 1.08805   0.711136  0.562207  1.32219
 1.43585   1.18082   0.701519  1.41524
 0.737899  0.714449  0.401329  0.806884

In [11]:
Array((B * A)')

4×4 Array{Float64,2}:
 1.10386   1.12131   1.01609   1.27638
 1.14231   0.690757  1.07862   0.996304
 0.744379  0.69683   0.863188  0.89087
 0.907992  0.950849  1.0607    0.952824

In [12]:
using LinearAlgebra

In [13]:
inv(A * B)

4×4 Array{Float64,2}:
 -0.247194  -0.58859   3.1484   -0.818734
 -0.891167  -1.70846  -1.12012   2.88484
  6.48013   -1.03159  -3.25507  -3.39368
 -9.4742     5.63612   2.0502    3.89334

In [14]:
inv(A) * inv(B)

4×4 Array{Float64,2}:
  1.66936    1.40897  -3.46469    0.860091
  2.93092   -1.40358  -0.285824  -1.07417
 -5.95198   -4.10421   3.1991     6.20634
  0.264064   3.41755   1.94901   -4.78226

In [15]:
inv(B * A)

4×4 Array{Float64,2}:
  1.66936    1.40897  -3.46469    0.860091
  2.93092   -1.40358  -0.285824  -1.07417
 -5.95198   -4.10421   3.1991     6.20634
  0.264064   3.41755   1.94901   -4.78226

In [16]:
inv(B) * inv(A)

4×4 Array{Float64,2}:
 -0.247194  -0.58859   3.1484   -0.818734
 -0.891167  -1.70846  -1.12012   2.88484
  6.48013   -1.03159  -3.25507  -3.39368
 -9.4742     5.63612   2.0502    3.89334

In [17]:
inv(Array((A * B)'))

4×4 Array{Float64,2}:
 -0.247194  -0.891167   6.48013  -9.4742
 -0.58859   -1.70846   -1.03159   5.63612
  3.1484    -1.12012   -3.25507   2.0502
 -0.818734   2.88484   -3.39368   3.89334

In [18]:
inv(Array(A' * B'))

4×4 Array{Float64,2}:
  1.66936    2.93092   -5.95198   0.264064
  1.40897   -1.40358   -4.10421   3.41755
 -3.46469   -0.285824   3.1991    1.94901
  0.860091  -1.07417    6.20634  -4.78226

In [19]:
inv(A') * inv(B')

4×4 Array{Float64,2}:
 -0.247194  -0.891167   6.48013  -9.4742
 -0.58859   -1.70846   -1.03159   5.63612
  3.1484    -1.12012   -3.25507   2.0502
 -0.818734   2.88484   -3.39368   3.89334

In [20]:
(inv(A) * inv(B))'

4×4 Adjoint{Float64,Array{Float64,2}}:
  1.66936    2.93092   -5.95198   0.264064
  1.40897   -1.40358   -4.10421   3.41755
 -3.46469   -0.285824   3.1991    1.94901
  0.860091  -1.07417    6.20634  -4.78226

*********
令$n=200$,使用$A=floor(10 * rand(n)); b = sum(A')'; z=ones(n,1)$,生成一个$n\times n$矩阵和两个$R^n$中的向量。

In [58]:
using BenchmarkTools
n = 1000 #change n=200, n=1000
A = floor.(10 * rand(n, n))
b = Array(sum(A', dims=1)')
z = ones(n, 1)

#= test time for two way: \ and inv =#
@btime A\b
@btime inv(A) * b;
x₁ = A\b
x₂ = inv(A) * b;

#test Accurate
println(maximum(abs.(x₁ - z)))
println(maximum(abs.(x₂ - z)))

  13.931 ms (4 allocations: 7.64 MiB)
  37.294 ms (6 allocations: 8.13 MiB)
2.129962872743363e-12
1.1823431123048067e-11


********
令$A=floor(10 * rand(6))$,根据构造，矩阵$A$将有整数元。将矩阵$A$的第6列更改，使得$A$为奇异的。

In [70]:
A = floor.(10 * rand(6,6))
B = A'
A[:, 6] = -sum(B[1:5, :], dims=1)'
A

6×6 Array{Float64,2}:
 3.0  4.0  1.0  3.0  2.0  -13.0
 7.0  5.0  7.0  8.0  6.0  -33.0
 2.0  6.0  6.0  2.0  5.0  -21.0
 0.0  4.0  5.0  1.0  6.0  -16.0
 3.0  7.0  6.0  5.0  5.0  -26.0
 6.0  6.0  4.0  4.0  7.0  -27.0

In [73]:
#a
x = ones(6, 1)
A*x

6×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [79]:
#
A * (x * collect(1:6)')

6×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [84]:
#c
C = floor.(10 * rand(6,6))
D = B + C
A * C

6×6 Array{Float64,2}:
  -67.0  -30.0  22.0  15.0  -22.0  11.0
 -144.0  -92.0  50.0  32.0  -44.0  40.0
  -81.0  -84.0  55.0  38.0  -28.0  22.0
  -52.0  -77.0  47.0  32.0   -9.0  16.0
 -109.0  -85.0  54.0  36.0  -33.0  20.0
 -123.0  -86.0  55.0  38.0  -38.0  38.0

In [85]:
A * D

6×6 Array{Float64,2}:
 141.0   483.0  347.0  259.0  384.0   434.0
 369.0  1220.0  875.0  659.0  982.0  1105.0
 244.0   741.0  601.0  460.0  637.0   704.0
 192.0   550.0  469.0  366.0  500.0   538.0
 297.0   941.0  719.0  545.0  787.0   861.0
 300.0   979.0  737.0  560.0  803.0   920.0

*********


In [98]:
B = Matrix{Float64}(I, 10, 10) - triu(ones(10,10), 1)
C = inv(B)
x = C[:,10]
B * x

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 1.0

In [100]:
#change a little
B[10,1] = -1/256
println(B)
B * x

[1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0; 0.0 1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0; 0.0 0.0 1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0; 0.0 0.0 0.0 1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0; 0.0 0.0 0.0 0.0 1.0 -1.0 -1.0 -1.0 -1.0 -1.0; 0.0 0.0 0.0 0.0 0.0 1.0 -1.0 -1.0 -1.0 -1.0; 0.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.0 -1.0 -1.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.0 -1.0; 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 -1.0; -0.00390625 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0]


10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

*********


In [109]:
using RowEchelon
A = floor.(10 * rand(6, 6))
b = floor.(20 * rand(6,1)) .- 10
A\b
rref([A b])[:,7] - A\b

6×1 Array{Float64,2}:
  2.220446049250313e-16
 -4.440892098500626e-16
  8.881784197001252e-16
  3.3306690738754696e-16
  3.885780586188048e-16
 -3.3306690738754696e-16

In [113]:
#b
A[:,3] = A[:, 1:2] * [4 3]'
rref([A b])
#no solution for Ax=b

6×7 Array{Float64,2}:
 1.0  0.0  4.0  0.0  0.0  0.0  0.0
 0.0  1.0  3.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0

**********
