# Runge-Kutta Methods

we know:

**Runge-Kutta Order 4**

In [1]:
function RungeKutta4(f::Function, a::Number, b::Number, N::Number, α::Number)
    h = (b - a) / N
    t, w = ones(N+1), ones(N+1)
    t[1], w[1] = a, α
    for i ∈ 1:N
        K₁ = h * f(t[i], w[i])
        K₂ = h * f(t[i] + h/2, w[i] + K₁/2)
        K₃ = h * f(t[i] + h/2, w[i] + K₂/2)
        K₄ = h * f(t[i] + h, w[i] + K₃)
        w[i + 1] = w[i] + (K₁ + 2K₂ + 2K₃ + K₄)/6
        t[i + 1] = a + i * h
    end
    return t, w
end

RungeKutta4 (generic function with 1 method)

In [10]:
#test
f(t, w) = w - t^2 + 1
RungeKutta4(f, 0, 2, 10, 0.5)[2]

11-element Array{Float64,1}:
 0.5
 0.8292933333333334
 1.2140762106666667
 1.6489220170416001
 2.1272026849479437
 2.6408226927287517
 3.1798941702322305
 3.7323400728549796
 4.283409498318405
 4.815085694579433
 5.305363000692653

In [7]:
function ModifiedEulerMethod(f::Function, a::Number, b::Number, N::Number, α::Number)
    h = (b - a) / N
    t, w = ones(N+1), ones(N+1)
    t[1], w[1] = a, α
    for i ∈ 1:N
        t[i + 1] = a + i * h
        w[i + 1] = w[i] + h/2 * (f(t[i], w[i]) + f(t[i+1], w[i] + h * f(t[i], w[i])))
    end
    return t, w
end

ModifiedEulerMethod (generic function with 1 method)

In [9]:
ModifiedEulerMethod(f, 0, 2, 10, 0.5)[2]

11-element Array{Float64,1}:
 0.5
 0.8260000000000001
 1.2069200000000002
 1.6372424000000003
 2.1102357280000006
 2.617687588160001
 3.149578857555201
 3.693686206217345
 4.235097171585161
 4.755618549333896
 5.233054630187353

***********
# Sets One


In [17]:
#1.b
f1(t, w) = 1 + (t - w)^2
pre = ModifiedEulerMethod(f1, 2, 3, 2, 1)[2]
Actual = [t + 1/(1-t) for t in [2, 2.5, 3]]
display([pre Actual])

3×2 Array{Float64,2}:
 1.0      1.0
 1.8125   1.83333
 2.48155  2.5

In [23]:
#1.d
f1(t, w) = cos(2*t)+sin(3*t)
pre = ModifiedEulerMethod(f1, 0, 1, 4, 1)
Actual = [1/2 * sin(2*t) - 1/3 * cos(3*t) + 4/3 for t in [0, 0.25, 0.5, 0.75, 1.0]]
display([pre[1] pre[2] Actual])

5×3 Array{Float64,2}:
 0.0   1.0      1.0
 0.25  1.3199   1.32915
 0.5   1.70703  1.73049
 0.75  2.00536  2.04147
 1.0   2.07708  2.11798

In [29]:
#3.d
f1(t, w) = -5 * w + 5 * t^2 + 2 * t
pre = ModifiedEulerMethod(f1, 0, 1, 10, 1/3)
Actual = [t^2 + 1/3 * exp(-5 * t) for t in 0:0.1:1]
display("t pre  Act")
display([pre[1] pre[2] Actual])

"t pre  Act"

11×3 Array{Float64,2}:
 0.0  0.333333  0.333333
 0.1  0.220833  0.212177
 0.2  0.174271  0.162626
 0.3  0.176419  0.164377
 0.4  0.216512  0.205112
 0.5  0.28782   0.277362
 0.6  0.386138  0.376596
 0.7  0.508836  0.500066
 0.8  0.654272  0.646105
 0.9  0.82142   0.813703
 1.0  1.00964   1.00225

In [31]:
#15.d
f1(t, w) = -5 * w + 5 * t^2 + 2 * t
pre = RungeKutta4(f1, 0, 1, 10, 1/3)
Actual = [t^2 + 1/3 * exp(-5 * t) for t in 0:0.1:1]
display("t pre  Act")
display([pre[1] pre[2] Actual])

"t pre  Act"

11×3 Array{Float64,2}:
 0.0  0.333333  0.333333
 0.1  0.212283  0.212177
 0.2  0.162765  0.162626
 0.3  0.164517  0.164377
 0.4  0.205241  0.205112
 0.5  0.277477  0.277362
 0.6  0.376698  0.376596
 0.7  0.500158  0.500066
 0.8  0.64619   0.646105
 0.9  0.813782  0.813703
 1.0  1.00232   1.00225

Water flows from an inverted conical tank with circular orifice at the rate

$$\frac{dx}{dt} = -0.6\pi r^2 \sqrt{2g} \frac{\sqrt{x}}{A(x)}$$

where r is the radius of the orifice, x is the height of the liquid level from the vertex of the cone, and A(x) is the area of the cross section of the tank x units above the orifice. Suppose $r = 0.1 ft, g = 32.1 ft/s^2$, and the tank has an initial water level of 8 ft and initial volume of $512(π/3) ft^3$. Use the Runge-Kutta method of order four to find the following.

a. The water level after 10 min with h = 20 s

b. When the tank will be empty, to within 1 min.

In [1]:
const r = 0.1
const g = 32.1

32.1